### ISSUE TITLE
[core] CTRL-C / KeyboardInterrupt should work even if pressed only once.

### ISSUE THREAD

**Issue by hartym** [python-bonobo/bonobo#13]
For now, two keyboardinterrupts are needed to stop a graph execution.

**Comment by hartym** [comment]
This should be fixed, need to verify and close.

**Comment by SanketDG** [comment]
This doesn't seem to work on the bonobo examples, it still needs two interrupts.

**Comment by hartym** [comment]
@SanketDG Ok, thanks. This one is urgent I'll look at it ASAP.

**Comment by vit-** [comment]
This thread shreds some light on why this happens https://stackoverflow.com/questions/29177490/how-do-you-kill-futures-once-they-have-started

**Comment by hartym** [comment]
Fixed in the upcoming 0.6
