### ISSUE TITLE
Allow to --install on a file if a requirements.txt file is in the same directory.

### ISSUE THREAD

**Issue by hartym** [python-bonobo/bonobo#133]
https://github.com/hartym/bonobo/blob/develop/bonobo/commands/run.py

(See the `raise RuntimeError('Cannot --install on a file (only available for dirs containing requirements.txt).')` line)

**Comment by alekzvik** [comment]
@hartym fixed in #148, you can close this one.

**Comment by hartym** [comment]
Thanks Alex!
