### ISSUE TITLE
Windows related issues

### ISSUE THREAD

**Issue by hartym** [python-bonobo/bonobo#142]
- [x] #134 -> no easy way to download example datasets (fixed by @Parthiv20)
- [x] Console output is quirky

**Comment by cw-andrews** [comment]
@hartym, 

Can you be more specific about how the console output is quirky?

**Comment by hartym** [comment]
It was displaying ANSI characters in windows console. This should be fixed by https://github.com/python-bonobo/bonobo/pull/153 and will be released with 0.5
