### ISSUE TITLE
statistics are hard to read on the Ubuntu standard terminal

### ISSUE THREAD

**Issue by spagoc** [python-bonobo/bonobo#165]
The  standard terminal on a Ubuntu workstation has a dark background. Bonobo uses a dark green/grey for its statistics. So a less dark gray text color for the Bonobo statistics could be more readable. Maybe is possible to find a color that is a good trade off on all the platforms. Lighter green/grey maybe?

**Comment by hartym** [comment]
LGTM, will be released in 0.5
