### ISSUE TITLE
Execute in parallel when possible.

### ISSUE THREAD

**Issue by TZubiri** [python-bonobo/bonobo#185]
In the following example, executing the transform nodes in parallel would bring the execution time from 15 seconds down to 3.

```
import time
import bonobo
import uuid

def extract():
    yield '1'
    yield '2'
    yield '3'
    yield '4'
    yield '5'

def transform(i):
    time.sleep(3)
    return i

def load(i):
    with open(i,'w') as f:
        f.write(i)

graph = bonobo.Graph(extract,transform,load)

bonobo.run(graph)
```

Here are the execution paths of the above Bonobo Graph
 
![screen](https://user-images.githubusercontent.com/8901363/31343980-b16714b4-ace7-11e7-9325-4cd0014d6034.jpg)

**Comment by TZubiri** [comment]
This might require either an interface to allow throttling (Possibly on a per Bonobo Node basis. Which is useful when performing http requests.
Disabling parallelization would be the same as throttling simultaneous executions to 1.

**Comment by hartym** [comment]
I think this is something that will be made possible by https://github.com/python-bonobo/bonobo/wiki/%5BRFC%5D-Transformation-Features

The idea is to consider by default we want first-in, first-out, but if one marks a node with a "Parallel" feature (like Parralel(4)(mynode)), then we can consider that FIFO is not a property of interest and skip it.

Same is True for other kind of "Features".

I'm not yet convinced by the name "Feature", and had no decision on syntax. Feel free to enhance (I know it's very early) the RFC, and let me know if it would be an acceptable soution to your feature request.

**Comment by hartym** [comment]
Discussion about this now in #236 (duplicate).
