### ISSUE TITLE
Console Output Text Disappears After Graph Completion.

### ISSUE THREAD

**Issue by cw-andrews** [python-bonobo/bonobo#214]
In some consoles/terminals the output text from running bonobo via the CLI disappears after graphi completion.

![screenshot from 2017-10-29 18-27-17](https://user-images.githubusercontent.com/6644591/32201291-93241e40-bdac-11e7-9dbf-74e8d13e885b.png)

**Comment by hartym** [comment]
Can you please share some informations about your environment, like what system, shell, bonobo version, python version, etc. ?

**Comment by cw-andrews** [comment]
Sure,

Solus with Budgie for the desktop environment, guake for the drop-down terminal, bash for the shell, and I am using the powerline extension as well.

**Comment by hartym** [comment]
Does that means windows? Sorry I'm not familiar with anythings except bash in what you said :)

**Comment by cw-andrews** [comment]
Romain,

Haha, no. I will try to give you some frame of reference.

1. Solus is a Linux distro.
https://solus-project.com/

2. Budgie is a desktop environment (the GUI).
https://solus-project.com/download/ 
(The Solus Budgie Edition)

3. Guake is a drop-down terminal for Linux written in Python 2
http://guake-project.org/

4. Powerline is a prompt for Bash, Zsh, and Fish shells which is also written in Python
https://github.com/banga/powerline-shell

**Comment by hartym** [comment]
Ok, I think that this is not related to your environment, and should be fixed in 0.6, at least after the huge PR I'm working on actually.

**Comment by hartym** [comment]
Fixed in 0.6
