### ISSUE TITLE
Documentation: permission denied on "SQLAlchemy extension for Bonobo" documentation page

### ISSUE THREAD

**Issue by buleoer** [python-bonobo/bonobo#237]
In page https://www.bonobo-project.org/with/sqlalchemy, the link "read the documentation" points to page http://docs.bonobo-project.org/en/latest/tutorial/tut04.html?__hstc=...., At this page, I have the following error:

Permission Denied

You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.

**Comment by hartym** [comment]
The correct URL for this page is now http://docs.bonobo-project.org/en/master/tutorial/0.5/tut04.html ; thank you for reporting the dead link, I'm currently rewriting most of the "getting started" docs for 0.6 ... «Permission Denied» is apparently a kind of 404 @ readthedocs.

Fixed on the website, too.
