### ISSUE TITLE
Quoting options format must be 'int'

### ISSUE THREAD

**Issue by alextop** [python-bonobo/bonobo#249]
https://github.com/python-bonobo/bonobo/blob/aa6e426768118b0be362e7404a1802e531008fab/bonobo/nodes/io/csv.py#L36

It throws an error when you assign anything to 'quoting=' param in constructor.

**Comment by hartym** [comment]
Indeed, my bad.

Can you submit a PR to fix that ? Switching str to int should be enough, seeing the definition of possible "quote" values:

```
QUOTE_ALL = 1
QUOTE_MINIMAL = 0
QUOTE_NONE = 3
QUOTE_NONNUMERIC = 2
```

**Comment by hartym** [comment]
Merged in master, will be released in next patch.
