### ISSUE TITLE
Distinguish between Error and Fatal errors in stats

### ISSUE THREAD

**Issue by benrudolph** [python-bonobo/bonobo#259]
## Versions

* Bonobo version:

    `bonobo v.0.6.1`

* Python version:

    `CPython 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609])`

* Platform:

    `Linux sp-airflow00 4.13.0-1005-azure #7-Ubuntu SMP Mon Jan 8 21:37:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
    `DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"`
   

I think one easy win for making error handling better in bonobo is to distinguish between error and fatal errors. Right now the stats dict considers a fatal err the same as a regular error. This would be useful in the context of Airflow that runs commands and if the command outputs a 0 it will continue the dag vs a 1 where it will fail the DAG. For fatal errors you almost certainly want the command to exit with an exit code of 1 because there's not point in continuing. For less drastic errors it's not entirely clear what to do, but at least the user can distinguish between the two.

What do you think of adding an additional key to stats for `fatal` and then increment that number? Perhaps a better abstraction would be to set a flag on the NodeExecutionContext itself. What do you think of something like that? Happy to take a shot at it if you think it's useful.

**Comment by hartym** [comment]
* For commands that have fatal errors, I do agree with you 100% that the system return code should be >0.
* For fatal counts, I'm not sure to agree with it. Not sure neither to disagree. The thing is, there cannot be more than one fatal in a context, so I don't really see the point of "counting". There is already a `defunct` attribute in node execution contexts that says if a fatal happened.

The caveat I see in current code is that node execution contexts track the "defunct" status, while the parent graph execution context does not. I think a good first step would be to have `GraphExecutionContext` implement `bonobo.execution.contexts.base.Lifecycle`. We can safely assume that a graph execution context is defunct if any of it's children is.

This would also allow to `sys.exit(1)` in the main block if `result.defunct`.

Does this would satisfy your use case? Let's discuss it, but anyhow, I _do_ think it's useful.

**Comment by benrudolph** [comment]
Ah I did not realize there was a `defunct` key already. Yes, I think it makes more sense to implement the `Lifecycle` context. Still getting my head wrapped around the different abstractions. Yea fatal count seems like a hack and really isn't that useful if you can tell the graph is `defunct`

**Comment by hartym** [comment]
I think that points out that I need to make an article / documentation page with schemas of all this, not so hard to understand graphically but I admit it may be a bit complicated without that.

Let me know if I can help on implementation side ?

**Comment by hartym** [comment]
Closed because `defunct` + `xstatus` already adresses that quite sufficiently. Also, there is no real benefit of counting fatals, as there is either one fatal (and then the execution is defunct) or none, can't be more.
