### ISSUE TITLE
What is the best way to do ETL from postgresql to another postgresql?

### ISSUE THREAD

**Issue by manel00** [python-bonobo/bonobo#262]
Hi!

I'm following both tutorials (bonobo 0.5 and 0.6) but seems to be little confusing and annoying...

Because 0.5 tutorial is closer to my needs but seems to be discontinued because on 0.6 has been changed everything (seems to me).

On bonobo version 0.6 seems to be to much different (started but need to be completed) and the tutorial with SQLAlchemy seems to be started but not continued (tutorial needs to be explained too much (functions) and need to be completed)

Please could you give me some advice to make it work? (If it's possible on 0.6)

Thank you very much

Regards

___________________________

ANOTHER QUESTION: 

Can you bring some examples of "bonobo_sqlalchemy.InsertOrUpdate" ???

It's really hard to know exactly what kind of parameters must be added to don't get errors on this method, please try to add some examples.

**Comment by hartym** [comment]
Tracker is for issues with the code, not usage questions. Please use SO for that.

**Comment by hartym** [comment]
http://docs.bonobo-project.org/en/master/extension/sqlalchemy.html
