### ISSUE TITLE
[console] fcntl Library Does Not Work in Native Windows

### ISSUE THREAD

**Issue by jelloslinger** [python-bonobo/bonobo#28]
When trying to run one of the basic examples from the documentation, I hit the following stack trace:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import bonobo
  File "C:\Users\mcopeland\Envs\bonobo\lib\site-packages\bonobo\__init__.py" line 17, in <module>
    from .core import __all__ as __all_core__
  File "C:\Users\mcopeland\Envs\bonobo\lib\site-packages\bonobo\core\__init_.py", line 3, in <module>
    from .bags import Bag, ErrorBag
  File "C:\Users\mcopeland\Envs\bonobo\lib\site-packages\bonobo\core\bags.py" line 3, in <module>
    from bonobo.util.tokens import Token
  File "C:\Users\mcopeland\Envs\bonobo\lib\site-packages\bonobo\util\__init__.py", line 6, in <module>
    import blessings
  File "C:\Users\mcopeland\Envs\bonobo\lib\site-packages\blessings\__init__.py" line 7, in <module>
    from fcntl import ioctl
ImportError: No module named 'fcntl'
```

It seems that the blessings library leverages fcntl which is used for file and IO control over Unix routines.  However, this leaves Windows users out of luck.

The following links have some tidbits of information:

http://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows
https://github.com/cs01/gdbgui/issues/18

This issue seems to plague many other projects (google "fcntl python windows" for a more thorough list of resources) and I haven't found any other examples of how this issue has been handled in a satisfactory manner.

**Comment by hartym** [comment]
Looks like a problem related to blessings (cf https://github.com/erikrose/blessings/issues/21). There are a few different options we can use, maybe colorama is a good one but there's a bit of work to rewrite the console plugin to use it, and support all cases (tty, non tty, width, no width, etc ...).

We need to setup windows CI at some point, too.

**Comment by hartym** [comment]
#29

**Comment by hartym** [comment]
Blessings now removed in favor of colorama starting from tag 0.2.1. Closing.

**Comment by cs01** [comment]
@jelloslinger have you tried http://stackoverflow.com/a/34504971/2893090? I implemented it in gdbgui (pygdbmi), but don't have Windows, so haven't been able to test it. The comments on SO indicate it works.
