### ISSUE TITLE
Jupyter Notebook Error : unrecognized arguments: -f 

### ISSUE THREAD

**Issue by gregobf** [python-bonobo/bonobo#291]
There is an issue with the Jupyter plugin.

I installed everything with

```
pip install bonobo[jupyter]
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter nbextension enable --py --sys-prefix bonobo.contrib.jupyter
```
And the lauched jupyter and created a Notebook containing the same code as in tutorial.py specified here python http://docs.bonobo-project.org/en/master/tutorial/1-init.html#create-an-etl-job and executed it.

I get the following error:

```
usage: ipykernel_launcher.py [-h] [--default-env-file DEFAULT_ENV_FILE]
                             [--default-env DEFAULT_ENV] [--env-file ENV_FILE]
                             [--env ENV]
ipykernel_launcher.py: error: unrecognized arguments: -f /Users/Gregory/Library/Jupyter/runtime/kernel-a58394f5-4d52-4a26-8377-d9a63062ca69.json

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
```

## Versions
* Bonobo version:
bonobo v.0.6.3 (in /anaconda3/envs/Bell-Osheaga/lib/python3.6/site-packages)

* Python version:
CPython 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]

* Platform:
Darwin MBP 18.2.0 Darwin Kernel Version 18.2.0: Tue Oct  2 22:38:23 PDT 2018; root:xnu-4903.221.1~12/RELEASE_X86_64 x86_64

**Comment by hartym** [comment]
The problems comes from the fact that you tried to run the console tutorial in a jupyter notebook. It can work, but you cannot use argument parsers here, so the main block should be slightly changed.
