### ISSUE TITLE
Possible race in implementation of `Exclusive`

### ISSUE THREAD

**Issue by kasei** [python-bonobo/bonobo#308]
I believe there's a race condition in the implementation of `bonobo.config.services.Exclusive`. When a new lock needs to be created, the code makes two accesses to the `Exclusive._locks` dictionary: a read to test for the lock's presence, and then a write to create the new lock. These two accesses are not protected by an internal lock, and open the possibility that two threads might end up creating two different locks for the same resource.

https://github.com/python-bonobo/bonobo/blob/5924de6a124ef7d38d73495132e7f206817e74c5/bonobo/config/services.py#L155-L156

**Comment by automape** [comment]
Indeed.

Can you implement a patch for this ? I guess that we could have another
lock to make sur the lock creation is not a parallel process, or we could
simply have the lock created at __init__ time (but that may need a lock for
lock creation anyway).

Thanks for spotting ;)
