### ISSUE TITLE
Any way to connect two existing Graph chains without adding new nodes?

### ISSUE THREAD

**Issue by kasei** [python-bonobo/bonobo#314]
To support fan-in on a graph chain that is eventually a sink, I'm using the `add_chain` support for the `_output` keyword argument. However, there doesn't seem to be any way to use `add_chain` to directly connect two *existing* chains without introducing a new node. I want to do something like this:

```python
graph.add_chain(_input=input_chain.output, _output=output_chain.input)
```

However, `add_chain` uses a conditional [`if len(nodes)`](https://github.com/python-bonobo/bonobo/blob/5924de6a124ef7d38d73495132e7f206817e74c5/bonobo/structs/graphs.py#L96) to guard all of the method logic. To work around this, I've had to use a no-op `identity` function:

```python
def identity(d):
    yield d

graph.add_chain(identity, _input=input_chain.output, _output=output_chain.input)
```

This is unfortunate for several reasons:

* Adds unnecessary code
* Adds runtime cost to run the no-op function
* Adds complexity to the graphviz visualization of the graph

Is there another way to connect two existing chains that doesn't involve `add_chain`? If not, can `add_chain` be improved to allow connecting the input and output, even if `nodes` is empty?

**Comment by hartym** [comment]
Let's find a way to make this possible, either using add chain with an empty list of nodes or a new api method.
