### ISSUE TITLE
[windows] pip install -e fails with encoding problem, both in win10 powershell or MINGW64

### ISSUE THREAD

**Issue by hartym** [python-bonobo/bonobo#32]
Not professional windows user here, quite the contrary. Maybe noob mistake.

Maybe related to the way I installed git ? I asked for "clone using windows encoding, commit using unix". Gonna try again with full unix, maybe.

```
PS C:\bb36\bonobo> pip install -e .
Obtaining file:///C:/bb36/bonobo
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\bb36\bonobo\setup.py", line 48, in <module>
        long_description=read('README.rst'),
      File "C:\bb36\bonobo\setup.py", line 15, in read
        content = f.read().strip()
      File "c:\users\ieuser\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\bb36\bonobo\
```

**Comment by hartym** [comment]
removing the readme before installing "fixes" the problem, but that need a fix.

**Comment by jelloslinger** [comment]
I had this problem as well.  Deleting the "bonobo character" from the README.rst fixes the problem.

**Comment by hartym** [comment]
@jelloslinger Should be fixed, and I could setup basic tests on windows platform using appveyor. Had to comment out a few things but at least we have CI on windows. Yeah ;)

Can you confirm it's better on your side too?
