### ISSUE TITLE
Output to multiple files. 

### ISSUE THREAD

**Issue by dovy** [python-bonobo/bonobo#373]
I’m curious if you can use any of your writers to output to a single file per row? I can’t seem to find any details on this. I need each row as its own file. When I try to do it myself in a pipeline function it goes all weird. Thank you.

**Comment by washad** [comment]
I was able to mock up a single file-per-row example and it seems to work just fine. The trick is working with the filenames -- but maybe you get that from the row? Anyway, I think it might be something in your implementation. 

```
def test(**options):
    graph = bonobo.Graph()
    graph.add_chain(
        ex_users,
        file_per_row_writer
    )
    return graph

def file_per_row_writer(*args):
    path = f"test_csv{random.randint(1, 1000000)}.csv"
    with open(path, 'w') as writer:
        writer.write(str(args))
```

**Comment by dovy** [comment]
Yes, I was able to get it working before you posted this. I should have closed the ticket. Thanks!  :)
