### ISSUE TITLE
bonobo_sqlalchemy.Select remove easy limit for oracle

### ISSUE THREAD

**Issue by TiagoVenancio** [python-bonobo/bonobo#389]
First I would like to congratulate the framework

I am facing a problem to perform a simple select (E.g: SELECT * FROM MY_TABLE) in oracle. The problem is that I always add the limit to the end of the query (Eg: SELECT * FROM MY_TABLE LIMIT 1000) returning the error: (cx_Oracle.DatabaseError) ORA-01036: illegal variable name / number [SQL: SELECT ID FROM MY_TABLE LIMIT 1000] .

How do I remove this select argument?

I know that this argument is used for performance purposes, but my application controls the number of lines.

**Comment by hartym** [comment]
Hello.

Unfortunately, I'm unable to answer support/help requests about bonobo and related software, and the bugtracker is only there to keep track of bugs/features. Additionally, I have no experience nor access to an infrastructure with oracle.

I can suggest you to read the source code, which is rather simple, and if it's not enough, you can either post something on stackoverflow, or simply write your own sql transformations.

Best regards.
