### ISSUE TITLE
Is the project being abondoned?

### ISSUE THREAD

**Issue by TeaDrinkingProgrammer** [python-bonobo/bonobo#424]
I really want to use the project, but it seems abondoned. Any updates on work being done for it? Would be a shame if the project were abandoned

**Comment by JasonCrowe** [comment]
I came to ask the same thing. Looking for an ETL package, but don't want to start with something that isn't active.

**Comment by TeaDrinkingProgrammer** [comment]
I ended up using JSON and Pandas, as that met my needs, but it seems like I was sadly right.

**Comment by leliel12** [comment]
+1

**Comment by fredericokremer** [comment]
what about a fork?

**Comment by hartym** [comment]
I confirm that I have no time to work on bonobo since a while. I'm completely open to giving maintain rights to someone who actually wants to invest the energy there.

**Comment by fredericokremer** [comment]
@hartym i can assume the mantain of the project. Bonobo is an important part of our internal pipelines in my laboratory, and we would be happy to colaborate on it's maintaince.

**Comment by hartym** [comment]
@fredericokremer This is awesome. I will email you so we can have a chat about it.

**Comment by transfluxus** [comment]
@hartym @fredericokremer that would be awesome

**Comment by Mathoholic** [comment]
@hartym can I fork it and improve and bring new features as you would have done if continued it...
I checked your website.

**Comment by hartym** [comment]
We had a chat with @fredericokremer who now have rights on all repositories. I'm very happy and confident that he will be able to give some fresh air and activity to the project. Cheers!

@Mathoholic You can always propose patches and pull requests.
